apiVersion: v1
kind: Pod
metadata:
  name: multi-toleration-fail
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
