apiVersion: v1
kind: Pod
metadata:
  name: noexec-allowed
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "devops"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
